# Generated by Django 5.2.15 on 2026-08-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_camera_certeza_minima_camera_intervalo_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(max_length=255),
        ),
    ]
