# Generated by Django 5.2.17 on 2026-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_camera_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraImage',
        ),
    ]
