# Generated by Django 5.2.17 on 2026-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_cameraimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='relevante',
            field=models.BooleanField(default=False),
        ),
    ]
